---
owner_id: Z05350071G03RV0PEHBLU
domain_filter: appref.end2end.link
paths:
 - platformservices/common
 - platformservices/appref1
tap:
  base:
    catalog:
      fqdn: https://github.com/jeffellin/tap-catalog/blob/main/catalog-info.yaml
    domain: tap-iterate.tanzu-aws-lab.winterfell.fun
  tapgui:
    domain: tap-gui.tap-iterate.tanzu-aws-lab.winterfell.fun
  learningcenter:
    domain: learningcenter.tap-iterate.tanzu-aws-lab.winterfell.fun
  cnr:
    domain: cnr.tap-iterate.tanzu-aws-lab.winterfell.fun
  