apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: route53-credentials
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
    kapp.k14s.io/change-rule.1: "upsert after upserting externaldns"
spec:
  toNamespaces:
  - tanzu-system-service-discovery
  - cert-manager
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: route53-credentials
  namespace: tanzu-system-service-discovery
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
    kapp.k14s.io/change-rule.1: "upsert after upserting externaldns"
spec:
  fromNamespace: tap-install