apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: route53-credentials
  namespace: tap-install-gitops
spec:
  toNamespaces:
  - tanzu-system-service-discovery
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: route53-credentials
  namespace: user2
spec:
  fromNamespace: tanzu-system-service-discovery