
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ def config():
---

namespace: tanzu-system-service-discovery

deployment:
  args:
    - --source=service
    - --source=ingress
    - --source=contour-httpproxy 
    - --policy=upsert-only 
    - --registry=txt
    - --txt-prefix=txt 
    - --provider=aws
    - --aws-zone-type=public 
    - --aws-prefer-cname
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: route53-credentials
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: route53-credentials
          key: aws_secret_access_key
  securityContext: {}
  volumeMounts: []
  volumes: []
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-values
  namespace: #@ data.values.externaldns.namespace
type: Opaque
stringData:
  values.yml: #@ yaml.encode(config())
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: externaldns-packageinstall
  namespace: #@ data.values.externaldns.namespace
  annotations:
    kapp.k14s.io/change-group: externaldns
    kapp.k14s.io/change-rule: "upsert after upserting externaldns-install/rbac"
spec:
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: #@ str(data.values.externaldns.version)
  serviceAccountName: externaldns-install-default-sa
  values:
  - secretRef:
      name: externaldns-values