apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: route53-credentials
  namespace: tap-install-gitops
spec:
  toNamespaces:
  - tanzu-system-service-discovery
  - cert-manager
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: route53-credentials
  namespace: tanzu-system-service-discovery
spec:
  fromNamespace: tap-install-gitops