
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ def config():
---

# The namespace in which to deploy ExternalDNS.
namespace: tanzu-system-service-discovery

# Deployment related configuration
deployment:
  args:
    - --source=service
    - --source=ingress
    - --source=contour-httpproxy # Provide this to enable Contour HTTPProxy support. Must have Contour installed or external-dns will fail.
    - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
    - --registry=txt
    - --txt-prefix=txt # disambiguates TXT records from CNAME records
    - --provider=aws
    - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
    - --aws-prefer-cname
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: route53-credentials
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: route53-credentials
          key: aws_secret_access_key
  securityContext: {}
  volumeMounts: []
  volumes: []
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-values
  namespace: tanzu-system-service-discovery
type: Opaque
stringData:
  values.yml: #@ yaml.encode(config())