#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ def config():
envoy:
  service: 
    type: LoadBalancer
    externalTrafficPolicy: Local
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-values
  namespace: #@ data.values.contour.namespace
type: Opaque
stringData:
  values.yml: #@ yaml.encode(config())
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour-packageinstall
  namespace: #@ data.values.contour.namespace
  annotations:
    kapp.k14s.io/change-group: contour
    kapp.k14s.io/change-rule.2: "upsert after upserting certmanager"
spec:
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: #@ str(data.values.contour.version)
  serviceAccountName: tap-install-gitops-sa
  values:
  - secretRef:
      name: contour-values

