#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: certmanager-packageinstall
  namespace: #@ data.values.certmanager.namespace
  annotations:
    kapp.k14s.io/change-group: certmanager
    kapp.k14s.io/change-rule.1: "upsert after upserting certmanager-install/rbac"
    kapp.k14s.io/change-rule.2: "upsert before upserting certmanager-install/cluster-issuer"
    
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: #@ str(data.values.certmanager.version)
  serviceAccountName: certmanager-install-default-sa

