#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: certmanager-packageinstall
  namespace: #@ data.values.certmanager.namespace
  annotations:
    kapp.k14s.io/change-group: certmanager
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: #@ str(data.values.certmanager.version)
  serviceAccountName: tap-install-gitops-sa

