#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")
---
#@ def config():
tap:
  catalog: github.com/catalog.yaml
  namespace: platform-svcs
  devNamespace: default
  domains:
    base: appref1.appref.end2end.link
    main: cnr.appref1.appref.end2end.link
    learningcenter: learningcenter.appref1.appref.end2end.link
    tapGui: tapgui.appref1.appref.end2end.link
  credentials:
    #! Pick one registry for downloading images: Tanzu Network or Pivotal Network
    #! (use tanzuNet as key).
    tanzuNet: #! Host to fetch the package fron
      host: registry.tanzu.vmware.com
      username: #@ data.values.tap.tanzunet.username
      password: #@ data.values.tap.tanzunet.password
    registry:
      repositories: 
        buildService: tanzu/tanzu-build-service
      host: registry.tanzu.vmware.com
      username: #@ data.values.tap.registry.username
      password: #@ data.values.tap.registry.password
    supplychainregistry:
      repositories: 
        ootbSupplyChain: tapb5
      host: registry.gcp.ellin.net
      username: #@ data.values.tap.supplychainregistry.username
      password: #@ data.values.tap.supplychainregistry.password
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-install-gitops
  namespace: platform-svcs
stringData:
  tap-secrets.yml: #@ yaml.encode(config())