#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")
---
#@ def config():
tap:
  catalog: https://github.com/jeffellin/tap-catalog/blob/main/catalog-info.yaml
  namespace: tap-install
  devNamespace: default
  domains:
    base: #@ data.values.tap.base.domain
    cnr: #@ data.values.tap.cnr.domain
    learningcenter: #@ data.values.tap.learningcenter.domain
    tapGui: #@ data.values.tap.tapgui.domain
  credentials:
    #! Pick one registry for downloading images: Tanzu Network or Pivotal Network
    #! (use tanzuNet as key).
    tanzuNet: #! Host to fetch the package fron
      host: registry.tanzu.vmware.com
      username: #@ data.values.tap.tanzunet.username
      password: #@ data.values.tap.tanzunet.password
    registry:
      repositories: 
        buildService: tap/tbs
      host: harbor.one.appref.end2end.link
      username: #@ data.values.tap.registry.username
      password: #@ data.values.tap.registry.password
    supplychainregistry:
      repositories: 
        ootbSupplyChain: tap/sc
      host: harbor.one.appref.end2end.link
      username: #@ data.values.tap.supplychainregistry.username
      password: #@ data.values.tap.supplychainregistry.password
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-install-gitops
  namespace: tap-install
stringData:
  tap-secrets.yml: #@ yaml.encode(config())