#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: tap-install
stringData:
  aws_access_key_id: #@ data.values.r53.access_key
  aws_secret_access_key: #@ data.values.r53.secret_key

