apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-gui-certificate
  namespace: tap-install
spec:
  secretName: tap-gui-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  commonName: "tap-gui.appref1.appref.end2end.link"
  dnsNames:
  - "tap-gui.appref1.appref.end2end.link"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: accelerator-certificate
  namespace: tap-install
spec:
  secretName: accelerator-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  commonName: "accelerator.appref1.appref.end2end.link"
  dnsNames:
  - "accelerator.appref1.appref.end2end.link"
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: accelerator-tls-secret
  namespace: tap-install
spec:
  delegations:
    - secretName: accelerator-tls-secret
      targetNamespaces:
      - "*"
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tap-gui-tls-secret
  namespace: tap-install
spec:
  delegations:
    - secretName: tap-gui-tls-secret
      targetNamespaces:
      - "*"
