apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-gui-certificate
  namespace: platform-svcs
spec:
  secretName: tap-gui-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  commonName: "tap-gui.appref1.appref.end2end.link"
  dnsNames:
  - "tap-gui.appref1.appref.end2end.link"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: accelerator-certificate
  namespace: platform-svcs
spec:
  secretName: accelerator-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  commonName: "accelerator.appref1.appref.end2end.link"
  dnsNames:
  - "accelerator.appref1.appref.end2end.link"

