apiVersion: v1
kind: Namespace
metadata:
  name: naomi
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: dev-ns-naomi
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: https://github.com/doddatpivotal/tapp-gitops-ref
      ref: origin/main
  template:
  - ytt:
      paths:
      - platformservices/dev-namespace
  deploy:
  - kapp: 
      intoNs: naomi
